### ISSUE TITLE
Unknown shorthand for block and inline combination

### ISSUE THREAD

**Issue by joelovasco** [csstools/stylelint-use-logical#1]
Thanks for all your work on this plugin.
Finding two shorthands that do not seem to be supported.

https://github.com/csstools/stylelint-use-logical/blob/016c7d43aa54fcdc10ba63ec5c3bb142b8089202/lib/maps.js#L12 

```
[['margin-top', `margin-${inline.start[dir]}`], 'margin-start'],
[['margin-bottom', `margin-${inline.end[dir]}`], 'margin-end'],
```
and

```
[['padding-top', `padding-${inline.start[dir]}`], 'padding-start'],
[['padding-bottom', `padding-${inline.end[dir]}`], 'padding-end']
```

Currently, these shorthand options are not in the [current draft](https://drafts.csswg.org/css-logical/).

**Comment by jonathantneal** [comment]
You are 100% correct, and I had never realized this, nor had anyone else brought this to my attention. In fact, I struggled to accept that I had even made such a mistake until I verified it in the current draft, the last draft, and the editor draft.

Worse yet, the [PostCSS Logical Plugin](https://github.com/jonathantneal/postcss-logical) is littered with transforms for properties ending with `-start` and `-end`.

The obvious solution is to remove the transforms and publish a breaking release for this plugin, and then to do the same for all of the others. This would potentially affect millions of weekly installs, so I can’t really comprehend its impact. As for this plugin, ceasing flags for potential `-start` and `-end` usage would be breaking but non-destructive.

Thank you. I’ll leave this open while I work on the fix, which may take some time.

**Comment by joelovasco** [comment]
@jonathantneal thanks for looking into this!

**Comment by joelovasco** [comment]
@jonathantneal found a couple of others for `inset`

```
[['top', inline.start[dir]], 'inset-start'],
[['bottom', inline.end[dir]], 'inset-end'],
```

**Comment by jonathantneal** [comment]
I will make these changes as part of the 2.0.0 work.

**Comment by fregante** [comment]
Were these fixed by 2.0.0?

**Comment by Jordan-Hall** [comment]
@jonathantneal I've added the full standard here https://github.com/Jordan-Hall/stylelint-use-logical. Do you want to take the PR so i can close my temporary npm package

**Comment by Jordan-Hall** [comment]
@jonathantneal & @hacknug  Is this still being maintained, I have another version now releasing along side and I've added a migration to move from unsupported logical to spec based

**Comment by romainmenke** [comment]
This was fixed as far as I can tell
