### ISSUE TITLE
Move plugin to monorepo?

### ISSUE THREAD

**Issue by romainmenke** [csstools/stylelint-use-logical#23]
@jonathantneal @Antonio-Laguna 

Should we migrate this plugin to the monorepo?
This seems like a good candidate as it is closely related to the logical polyfill plugins.

Existing plugins in the monorepo live here : https://github.com/csstools/postcss-plugins/tree/main/plugins-stylelint

To do so both @Antonio-Laguna and me would need to receive publish access for https://www.npmjs.com/package/stylelint-use-logical

**Comment by tobyperplex** [comment]
Sure, support for stylelint 16 would also be nice :)

**Comment by romainmenke** [comment]
After taking a look I think there are two fundamental issues with this plugin.

- it converts longhands to shorthands
- it has config for direction (`ltr` vs. `rtl`)

This means that it doesn't simply promote logical props and values over physical it also mutates the source in a way that changes the outcome.

I think that both are too opinionated and not a good fit for the monorepo.
So going to keep this separate.
