### ISSUE TITLE
Plugin not supported when using Stylelint >16

### ISSUE THREAD

**Issue by arvidnilber** [csstools/stylelint-use-logical#25]
Stylelint depcreated the use of CommonJS in version 16. This plugin is using CommonJS after bundling it, so it stops us from upgrading to v16. 

`CommonJS plugins are deprecated (node_modules/stylelint-use-logical/index.cjs")`

This is how `stylelint-use-logical/index.cjs` looks like;:

```javascript
'use strict';

var stylelint = require('stylelint');

const inline = {
	start: { ltr: 'left', rtl: 'right' },
	end: { ltr: 'right', rtl: 'left' }
};
```

**Comment by dwightjack** [comment]
@arvidnilber the plugin is bundled in both CJS and ESM. What seems to not work properly (or at least it looks to me to not work properly) is the resolution of the [correct entry point](https://github.com/csstools/stylelint-use-logical/blob/3f0a30c9a36185115e9c54f8c545d628a1bda9cb/package.json#L14).

I have solved the issue by temporarily patching the source code with [`pnpm patch`](https://pnpm.io/cli/patch) (I think there's a similar command in yarn and, for npm, you can use https://www.npmjs.com/package/patch-package).

**Comment by romainmenke** [comment]
Thank you for reporting this.

I've changed this to :

https://github.com/csstools/stylelint-use-logical/blob/fdd3f4585d2c3649eec68738b06e9e8505faabd7/package.json#L12-L16

Please let me now if this update causes any new issues.
