### ISSUE TITLE
Outdated peer-dependency of styleline

### ISSUE THREAD

**Issue by jens-duttke** [csstools/stylelint-use-logical#7]
The current version of `stylelint` is `13.7.0`, but `stylelint-use-logical` still requires an outdated version, even if it works fine with `13.7.0`:
```
npm WARN stylelint-use-logical@1.1.0 requires a peer of stylelint@^9.6.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by romainmenke** [comment]
We just release version `2.1.1` : https://www.npmjs.com/package/stylelint-use-logical

Thank you for reporting.
