### ISSUE TITLE
v2 not published to npm

### ISSUE THREAD

**Issue by WickyNilliams** [csstools/stylelint-use-logical#9]
Just an FYI: I assume someone forgot to publish to npm. The latest published version is `1.1.0`. See https://www.npmjs.com/package/stylelint-use-logical?activeTab=versions

**Comment by jonathantneal** [comment]
Hey @WickyNilliams, a few months ago I published v2, but I didn’t catch this open issue to update it. I’m sorry about that. Just for completeness sake — it was published.

Thank you for the reminder, and I’m sorry to everyone that it was so delayed.

**Comment by WickyNilliams** [comment]
Cool, thanks for the update. I actually ended up using [a fork of this project](https://github.com/Jordan-Hall/stylelint-use-logical-spec) in the end, for reasons i no longer remember.
